#!/bin/bash

HOST_OS="linux"
HOST_ARCH="x86_64"

export AR=arm-linux-gnueabihf-ar
export LINK=arm-linux-gnueabihf-g++
export CC="arm-linux-gnueabihf-gcc -O2 -pipe -marm -march=armv6j -mfpu=vfp -mfloat-abi=hard"
export CXX="arm-linux-gnueabihf-g++ -O2 -pipe -marm -march=armv6j -mfpu=vfp -mfloat-abi=hard"

GYP_DEFINES="target_arch=arm"
GYP_DEFINES+=" arm_version=6"
GYP_DEFINES+=" v8_target_arch=arm"
GYP_DEFINES+=" host_os=linux"
export GYP_DEFINES

./configure --fully-static --prefix=../install --cross-compiling --without-npm  --dest-cpu=arm --dest-os=linux --without-node-snapshot --without-ssl --without-inspector --without-node-code-cache --verbose --without-snapshot
